BMS:
  port: can0
  portrate: 250000
  lowVoltageWarning: 48.5
  readtimeout: 10000
inverter:
  port: can1
  portrate: 500000
cellbalancing:
  interval-days: 2
  hold-soc: 99
  minutes: 35
mqtt:
  host: 10.10.30.10
  port: 1883
logging:
  loglevel: info
  logfile: log/BMS2Inverter.log
